[package]
name = "yup-oauth2-metadata"
version = "0.0.1"
edition = "2018"

[dependencies]
yup-oauth2 = "1.0.12"
log = "0.4"
hyper = "0.13.5"
hyper-rustls = "0.20"
serde_json = "1.0"
futures = "0.3.5"
tokio = { version = "0.2", features = ["macros"] }

[lib]
name = "metadata"
path = "src/lib.rs"